#!/usr/bin/env node
import {execFileSync} from "node:child_process";
import {createHash} from "node:crypto";
import {existsSync,readFileSync,writeFileSync,mkdirSync,copyFileSync,realpathSync} from "node:fs";
import {resolve,relative,dirname,join} from "node:path";

const repo=realpathSync(process.cwd()), stateDir=join(repo,".runner"), stateFile=join(stateDir,"state.json");
const args=process.argv.slice(2), command=args[0]||"help";
const value=(name)=>{const i=args.indexOf("--"+name);return i<0?null:args[i+1]||null};
const fail=(message,code=2)=>{console.error(JSON.stringify({ok:false,error:message}));process.exit(code)};
const inside=(p)=>{const abs=resolve(repo,p),r=relative(repo,abs);return r===""||(!r.startsWith("..")&&!r.startsWith("/"))};
const repoPath=(p)=>{if(!p||!inside(p))fail("Chemin hors du dépôt refusé.",3);return resolve(repo,p)};
const blocked=/(^|\/)(\.env|\.git|secrets?|credentials?|node_modules)(\/|$)|(^|\/)(wrangler\.jsonc|package-lock\.json)$/i;
const sensitive=/(secret|token|password|api[_-]?key|dns|production|deploy|binding|r2|d1|auth)/i;
const readState=()=>{if(!existsSync(stateFile))return {version:1,modules:[],plans:[],events:[]};try{return JSON.parse(readFileSync(stateFile,"utf8"))}catch{return fail("État du runner invalide.",4)}};
const saveState=(s)=>{mkdirSync(stateDir,{recursive:true});writeFileSync(stateFile,JSON.stringify(s,null,2)+"\n","utf8")};
const hash=(b)=>createHash("sha256").update(b).digest("hex");
const event=(s,type,data={})=>s.events.push({type,at:new Date().toISOString(),...data});
const git=(...a)=>{try{return execFileSync("git",a,{cwd:repo,encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim()}catch{return null}};
const gitRepo=Boolean(git("rev-parse","--is-inside-work-tree"));
const run=(cmd,a)=>{if(cmd!=="node")fail("Commande non allowlistée.",3);return execFileSync(cmd,a,{cwd:repo,encoding:"utf8",stdio:"pipe",timeout:120000})};
const tests={syntax:["--check","worker.js"],runner:["--test","tests/mentor-runner.test.mjs","tests/autonomy-module-registry.test.mjs"]};
function inspect(){const files=[];for(const f of ["worker.js","wrangler.jsonc","package.json","runner/module-registry.json"]){if(existsSync(resolve(repo,f)))files.push({path:f,bytes:readFileSync(resolve(repo,f)).length,sha256:hash(readFileSync(resolve(repo,f)))});}return {ok:true,state:"proposition",repo,git_repository:gitRepo,files};}
function registerFixture(s){if(!s.modules.some(m=>m.id==="test_module"))s.modules.push({id:"test_module",version:"0.1.0",dependencies:[],permissions:["read_repo","write_repo","run_tests"],routes:[],bindings:[],health_check:"node --check runner/fixtures/test-module.mjs",health_files:["runner/fixtures/test-module.mjs"],rollback:"restaurer la sauvegarde du plan",state:"proposition"});}
function plan(s){const objective=value("objective")||"Cycle fictif du runner local";if(sensitive.test(objective))fail("Objectif sensible refusé.",3);const listed=(value("files")||"runner/fixtures/test-module.mjs").split(",").map(x=>x.trim()).filter(Boolean);if(listed.some(f=>!inside(f)||blocked.test(f)))fail("Fichier hors périmètre ou sensible refusé.",3);const id="plan-"+Date.now(),p={id,objective,files:listed,state:"proposition",authorization:"required",created_at:new Date().toISOString(),diff:value("patch")||null,tests:["syntax","runner"],backup:null,branch:null};s.plans.push(p);event(s,"plan_proposed",{id,files:listed});return p;}
function authorize(s){const p=s.plans.find(x=>x.id===value("id"));if(!p)fail("Plan introuvable.",4);if(value("approve")!=="yes")fail("Autorisation explicite requise : --approve yes",3);p.state="autorisation requise";p.authorization="approved";event(s,"plan_authorized",{id:p.id});return p;}
function backup(s,p){const dir=join(stateDir,"backups",p.id);mkdirSync(dir,{recursive:true});p.files.forEach(f=>{const src=repoPath(f);if(existsSync(src)){const dst=join(dir,f);mkdirSync(dirname(dst),{recursive:true});copyFileSync(src,dst)}});p.backup=relative(repo,dir);p.branch=gitRepo?(git("branch","--show-current")||null):"filesystem-backup";}
function applyUnified(text){const blocks=text.split(/(?=^diff --git )/m).filter(Boolean);for(const block of blocks){const m=block.match(/\+\+\+ b\/([^\n]+)/);if(!m)fail("Diff sans fichier cible refusé.",3);const file=repoPath(m[1]);let current=readFileSync(file,"utf8");const h=block.match(/@@[^\n]*\n([\s\S]*)/);if(!h)fail("Diff sans hunk refusé.",3);const lines=h[1].split("\n");const old=lines.filter(x=>x.startsWith(" ")||x.startsWith("-")).map(x=>x.slice(1)).join("\n");const fresh=lines.filter(x=>x.startsWith(" ")||x.startsWith("+")).map(x=>x.slice(1)).join("\n");if(!current.includes(old))fail("Le contenu attendu par le diff est absent.",3);current=current.replace(old,fresh);writeFileSync(file,current,"utf8");}}
function apply(s){const p=s.plans.find(x=>x.id===value("id"));if(!p)fail("Plan introuvable.",4);if(p.authorization!=="approved")fail("Plan non autorisé.",3);const patch=value("patch")||p.diff;if(!patch)fail("Diff obligatoire.",2);if(!inside(patch)||blocked.test(patch))fail("Diff hors périmètre refusé.",3);const text=readFileSync(repoPath(patch),"utf8");if(/(^|\n)\+\+\+\s+\/|(^|\n)---\s+\/|\.\.(\/|\\)/.test(text))fail("Diff contenant un chemin hors dépôt refusé.",3);backup(s,p);p.state="en cours";saveState(s);try{if(gitRepo){const patchFile=join(stateDir,p.id+".diff");writeFileSync(patchFile,text);execFileSync("git",["apply","--check",patchFile],{cwd:repo,stdio:"pipe"});execFileSync("git",["apply",patchFile],{cwd:repo,stdio:"pipe"})}else applyUnified(text);event(s,"patch_applied",{id:p.id});return p}catch{p.state="échec";event(s,"patch_failed",{id:p.id});fail("Application du diff échouée.",1)}}
function test(s){const p=s.plans.find(x=>x.id===value("id"));if(!p)fail("Plan introuvable.",4);const name=value("test")||"syntax";if(!Object.hasOwn(tests,name))fail("Test non allowlisté.",3);try{run("node",tests[name]);p.state="tests réussis";p.last_test={name,at:new Date().toISOString()};event(s,"tests_passed",{id:p.id,name});return p}catch(e){p.state="échec";event(s,"tests_failed",{id:p.id,name,error:String(e.stderr||e.message).slice(0,500)});fail("Tests échoués.",1)}}
function activate(s){const p=s.plans.find(x=>x.id===value("id"));if(!p)fail("Plan introuvable.",4);if(p.state!=="tests réussis")fail("Activation refusée avant tests réussis.",3);p.state="déployé";event(s,"module_activated",{id:p.id});return p;}
function rollback(s){const p=s.plans.find(x=>x.id===value("id"));if(!p||!p.backup)fail("Sauvegarde introuvable.",4);const dir=repoPath(p.backup);for(const f of p.files){const src=join(dir,f);if(existsSync(src)){const dst=repoPath(f);mkdirSync(dirname(dst),{recursive:true});copyFileSync(src,dst)}}p.state="rollback";event(s,"rollback_completed",{id:p.id});return p;}
function cycle(s){registerFixture(s);const p=plan(s);p.diff="runner/fixtures/test-module.diff";p.authorization="approved";p.state="autorisation requise";event(s,"cycle_ready",{id:p.id});return {ok:true,state:p.state,plan:p,notice:"authorize/apply/test/activate/rollback"};}
let s=readState(),out;
if(command==="inspect")out=inspect();else if(command==="modules"){registerFixture(s);out={ok:true,modules:s.modules};}else if(command==="propose")out=plan(s);else if(command==="authorize")out=authorize(s);else if(command==="apply")out=apply(s);else if(command==="test")out=test(s);else if(command==="activate")out=activate(s);else if(command==="rollback")out=rollback(s);else if(command==="cycle")out=cycle(s);else fail("Commande refusée. Utiliser inspect, modules, propose, authorize, apply, test, activate, rollback ou cycle.",2);
saveState(s);console.log(JSON.stringify(out,null,2));
