import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

test('AI SOV auto-close requires an always-on AI alternative and never depends on the owner PC', async()=>{
  const source=await readFile(new URL('../../.github/workflows/mel-sov-ai-auto-close.yml',import.meta.url),'utf8');
  assert.ok(source.includes("cron: '11 * * * *'"));
  assert.ok(source.includes('push:'));
  assert.ok(source.includes('- main'));
  assert.ok(source.includes("- 'src/portability/**'"));
  assert.ok(source.includes('refresh=ai'));
  assert.equal(source.includes('refresh=ai_local'),false);
  assert.ok(source.includes('MEL_SOV_AI_ALWAYS_ON_PREVALIDATED'));
  assert.ok(source.includes('MEL_SOV_AI_ALWAYS_ON_NOT_READY'));
  assert.ok(source.includes('MEL_SOV_AI_ALWAYS_ON_ALTERNATIVE_REQUIRED'));
  assert.ok(source.includes('MEL_SOV_AI_LOCAL_OPTIONAL_NOT_AUTO_STARTED'));
  assert.ok(source.includes('MEL_SOV_01_DONE_VERIFIED_ELIGIBLE'));
  assert.ok(source.includes('ready_layer_count||0)===10'));
  assert.ok(source.includes('layer_count||0)===10'));
  assert.ok(source.includes('ai_low_refusal_ready===true'));
  assert.ok(source.includes("AI_LOW_REFUSAL_READY='+(d?.ai_low_refusal_ready===true?'1':'0')"));
  assert.ok(source.includes('MEL_SOV_AI_ALWAYS_ON_LOW_REFUSAL_ALREADY_READY'));
  assert.ok(source.includes('release_transition_supersedes_run'));
  assert.ok(source.includes('MEL_SOV_AI_SUPERSEDED_BY_NEW_RELEASE'));
  assert.ok(source.includes('BOOTSTRAP_AUTH_REQUIRED'));
  assert.ok(source.includes('abort_if_release_transition'));
  assert.ok(source.includes('exit 47'));
  assert.ok(source.includes('MEL_SOV_AI_FINAL_GATE_NOT_CLOSED'));
  assert.ok(source.includes('process.exit(45)'));
  assert.ok(source.includes('MEL_SOV_AI_CLOSED_10_OF_10'));
  assert.equal(source.includes('OLLAMA_BOOTSTRAP_PROCESS_EXITED'),false);
  assert.equal(source.includes('COMPANION_ENGINE_UPDATE_REQUIRED'),false);
  assert.equal(source.includes('MEL_SOV_AI_BOOTSTRAP_WAIT'),false);
  assert.equal(source.includes('MEL_SOV_AI_WAITING_FOR_COMPANION'),false);
  assert.equal(source.includes('refresh=source_control'),false);
  assert.equal(source.includes('refresh=infrastructure'),false);
  assert.equal(source.includes('refresh=backup_restore'),false);
});
