import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

test('AI SOV auto-close watches only the missing AI layer and preserves the 10/10 gate', async()=>{
  const source=await readFile(new URL('../../.github/workflows/mel-sov-ai-auto-close.yml',import.meta.url),'utf8');
  assert.ok(source.includes("cron: '11 * * * *'"));
  assert.ok(source.includes('push:'));
  assert.ok(source.includes('- main'));
  assert.ok(source.includes("- 'src/portability/**'"));
  assert.ok(source.includes('refresh=ai_local'));
  assert.ok(source.includes('refresh=ai'));
  assert.ok(source.includes('MEL_SOV_AI_CONFIGURED_PREVALIDATED'));
  assert.ok(source.includes('MEL_SOV_AI_CONFIGURED_NOT_READY'));
  assert.ok(source.includes('MEL_SOV_01_DONE_VERIFIED_ELIGIBLE'));
  assert.ok(source.includes('ready_layer_count||0)===10'));
  assert.ok(source.includes('layer_count||0)===10'));
  assert.ok(source.includes('ai_low_refusal_ready===true'));
  assert.ok(source.includes("AI_LOW_REFUSAL_READY='+(d?.ai_low_refusal_ready===true?'1':'0')"));
  assert.ok(source.includes('MEL_SOV_AI_LOW_REFUSAL_ALREADY_READY'));
  assert.ok(source.includes('AI_BOOTSTRAP_WAITS=0'));
  assert.ok(source.includes('AI_ENGINE_UPDATE_WAITS=0'));
  assert.ok(source.includes('while [ "$AI_ATTEMPT" -lt 28 ]'));
  assert.ok(source.includes('AI_ENGINE_UPDATE_WAITS" -lt 14'));
  assert.ok(source.includes('AI_DIAGNOSTICS'));
  assert.ok(source.includes('native='));
  assert.ok(source.includes('engine='));
  assert.ok(source.includes('refresh_error='));
  assert.ok(source.includes('AI_BOOTSTRAP_WAITS" -lt 8'));
  assert.ok(source.includes('SOVEREIGNTY_AI_LOCAL_BOOTSTRAP_PENDING'));
  assert.ok(source.includes('MEL_SOV_AI_BOOTSTRAP_WAIT'));
  assert.ok(source.includes('sleep 45'));
  assert.ok(source.includes('MEL_SOV_AI_LOCAL_BOOTSTRAP_STILL_PENDING'));
  assert.ok(source.includes('exit 42'));
  assert.ok(source.includes('MEL_SOV_AI_LOCAL_RUNTIME_UNAVAILABLE'));
  assert.ok(source.includes('exit 43'));
  assert.ok(source.includes('MEL_SOV_AI_REFRESH_FAILED'));
  assert.ok(source.includes('exit 44'));
  assert.ok(source.includes('MEL_SOV_AI_FINAL_GATE_NOT_CLOSED'));
  assert.ok(source.includes('process.exit(45)'));
  assert.ok(source.includes('MEL_SOV_AI_CLOSED_10_OF_10'));
  assert.equal(source.includes('MEL_SOV_AI_LOW_REFUSAL_READY_FINAL_GATE_PENDING'),false);
  assert.equal(source.includes('MEL_SOV_AI_WAITING_FOR_COMPANION'),false);
  assert.equal(source.includes('AI_COVERED='),false);
  assert.equal(source.includes('refresh=source_control'),false);
  assert.equal(source.includes('refresh=infrastructure'),false);
  assert.equal(source.includes('refresh=backup_restore'),false);
});
