import test from 'node:test'; import assert from 'node:assert/strict';
import worker from '../../src/index.js'; import { sqliteD1 } from '../helpers/sqlite-d1.mjs';
import { createGen2Runtime } from '../../src/core/orchestrator/gen2-runtime.js'; import { createLocalServices } from '../../src/core/orchestrator/local-services.js'; import { MediaService } from '../../src/media/media-service.js';
test('single local MEL acceptance flow crosses product and extension runtimes', async()=>{
 const DB=sqliteD1(), env={DB,MELITURGOS_USER:'test',MELITURGOS_PASSWORD:'test-only',AI:{async run(model,input){return {response:`mock:${input.messages.at(-1).content}`}}}}; const h={authorization:`Basic ${Buffer.from('test:test-only').toString('base64')}`};
 try { const cid='acceptance'; const req=t=>new Request('http://x/api/chat',{method:'POST',headers:{...h,'content-type':'application/json','x-conversation-id':cid},body:JSON.stringify({text:t,conversation_id:cid})}); assert.equal((await worker.fetch(req('Retenir: Orion est prioritaire'),env)).status,200); assert.equal((await worker.fetch(req('Quel projet est prioritaire ?'),env)).status,200); const history=(await DB.prepare('SELECT * FROM archive_messages WHERE conversation_id=?').bind(cid).all()).results; assert.equal(history.length,4); const runtime=createGen2Runtime(); const manifest={id:'accept-plugin',name:'accept',version:'1.0.0',description:'x',author:'test',capabilities:[],permissions:[],secrets_required:[],dependencies:[],entrypoint:'main.js',healthcheck:'health',risk:'LOW'}; runtime.plugins.register(manifest,async i=>({value:i.value})); assert.deepEqual(await runtime.plugins.execute(manifest.id,{value:'plugin'}, {owner:'test',permissions:[],requestId:crypto.randomUUID()}),{value:'plugin'}); runtime.modules.register({...manifest,id:'accept-module'},async i=>({value:i.value})); runtime.modules.activate('accept-module'); assert.deepEqual(await runtime.modules.run('accept-module',{value:'module'},{owner:'test',permissions:[],requestId:crypto.randomUUID()}),{value:'module'}); runtime.agents.register('accept-agent',[{capability:'echo',input:{value:'agent'}}]); assert.equal((await runtime.agents.run('accept-agent',{owner:'test',permissions:[],requestId:crypto.randomUUID()})).results[0].value,'agent'); const local=createLocalServices(); const a=await local.automations.create({type:'EVENT'}); await local.automations.enable({id:a.id}); assert.equal((await local.automations.run({id:a.id})).status,'SUCCEEDED'); assert.equal((await local.professor.score()).score,1);
 const rows=new Map(), objects=new Map();
 const db={ prepare(sql) { return { bind(...args) { return { async run() { if(sql.startsWith('INSERT')) rows.set(args[0],{id:args[0],r2_key:args[7],filename:args[3]}); if(sql.startsWith('DELETE')) rows.delete(args[0]); }, async first() { return rows.get(args[0])||null; } }; } }; } };
 const bucket={async put(k,b){objects.set(k,b)},async get(k){return objects.get(k)},async delete(k){objects.delete(k)}};
 const media=new MediaService({DB:db,MEDIA_BUCKET:bucket}); const m=await media.upload({bytes:new Uint8Array([1]),mime_type:'application/octet-stream',filename:'a.bin'}); assert.ok(await media.get({id:m.id})); await media.delete({id:m.id});
 } finally {DB.close()} });
