CREATE TABLE memories (id INTEGER PRIMARY KEY AUTOINCREMENT,created_at INTEGER NOT NULL,kind TEXT NOT NULL DEFAULT 'episodic',content TEXT NOT NULL,importance REAL NOT NULL DEFAULT 0.5,source TEXT NOT NULL DEFAULT 'chat',metadata TEXT NOT NULL DEFAULT '{}',fingerprint TEXT, confidence REAL NOT NULL DEFAULT 0.5, valid_from INTEGER, valid_until INTEGER, supersedes_id INTEGER, provenance TEXT NOT NULL DEFAULT '');
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE interactions (id INTEGER PRIMARY KEY AUTOINCREMENT,created_at INTEGER NOT NULL,user_text TEXT NOT NULL,assistant_text TEXT NOT NULL,model TEXT NOT NULL,feedback INTEGER,correction TEXT, provenance TEXT NOT NULL DEFAULT 'chat');
CREATE TABLE _cf_METADATA (
        key INTEGER PRIMARY KEY,
        value BLOB
      );
CREATE TABLE professor_sessions (id TEXT PRIMARY KEY,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'active',goal TEXT NOT NULL DEFAULT '', last_used_at INTEGER, provenance TEXT NOT NULL DEFAULT 'professor');
CREATE TABLE professor_turns (id INTEGER PRIMARY KEY AUTOINCREMENT,session_id TEXT NOT NULL,created_at INTEGER NOT NULL,kind TEXT NOT NULL DEFAULT 'question',question TEXT NOT NULL,answer TEXT NOT NULL,memories_json TEXT NOT NULL DEFAULT '[]',tools_json TEXT NOT NULL DEFAULT '{}',critique TEXT,correction TEXT,improved_answer TEXT, confidence REAL NOT NULL DEFAULT 0.5, last_used_at INTEGER, provenance TEXT NOT NULL DEFAULT 'professor_session', correction_id INTEGER, retest_id INTEGER, passed INTEGER, explanation_variant INTEGER NOT NULL DEFAULT 0,FOREIGN KEY(session_id) REFERENCES professor_sessions(id));
CREATE TABLE professor_lessons (id INTEGER PRIMARY KEY AUTOINCREMENT,session_id TEXT NOT NULL,turn_id INTEGER NOT NULL,created_at INTEGER NOT NULL,lesson TEXT NOT NULL,rationale TEXT NOT NULL DEFAULT '',validated INTEGER NOT NULL DEFAULT 1,memory_id INTEGER, learning_status TEXT NOT NULL DEFAULT 'accepted', proposal_reason TEXT NOT NULL DEFAULT '', importance REAL NOT NULL DEFAULT 1, confidence REAL NOT NULL DEFAULT 0.5, last_used_at INTEGER, provenance TEXT NOT NULL DEFAULT 'professor_session_lesson', correction_turn_id INTEGER, retest_id INTEGER, understanding_status TEXT NOT NULL DEFAULT 'pending_retest',FOREIGN KEY(session_id) REFERENCES professor_sessions(id),FOREIGN KEY(turn_id) REFERENCES professor_turns(id));
CREATE TABLE knowledge_sources (id TEXT PRIMARY KEY,name TEXT NOT NULL,kind TEXT NOT NULL,author TEXT NOT NULL DEFAULT '',url TEXT NOT NULL DEFAULT '',source_date INTEGER,rights TEXT NOT NULL DEFAULT 'read',status TEXT NOT NULL DEFAULT 'active',content_hash TEXT NOT NULL,confidence REAL NOT NULL DEFAULT 0.7,created_at INTEGER NOT NULL,revoked_at INTEGER,metadata TEXT NOT NULL DEFAULT '{}');
CREATE TABLE knowledge_passages (id INTEGER PRIMARY KEY AUTOINCREMENT,source_id TEXT NOT NULL,ordinal INTEGER NOT NULL,title TEXT NOT NULL DEFAULT '',text TEXT NOT NULL,content_hash TEXT NOT NULL,source_date INTEGER,confidence REAL NOT NULL DEFAULT 0.7,rights TEXT NOT NULL DEFAULT 'read',active INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL,UNIQUE(source_id,content_hash),FOREIGN KEY(source_id) REFERENCES knowledge_sources(id));
CREATE TABLE knowledge_imports (id TEXT PRIMARY KEY,source_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'queued',idempotency_key TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,passage_count INTEGER NOT NULL DEFAULT 0,error TEXT NOT NULL DEFAULT '',FOREIGN KEY(source_id) REFERENCES knowledge_sources(id));
CREATE TABLE learning_profiles (id TEXT PRIMARY KEY,owner TEXT NOT NULL,level TEXT NOT NULL DEFAULT 'unspecified',preferences TEXT NOT NULL DEFAULT '{}',goals TEXT NOT NULL DEFAULT '[]',domains TEXT NOT NULL DEFAULT '[]',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE learning_topics (id INTEGER PRIMARY KEY AUTOINCREMENT,profile_id TEXT NOT NULL,topic TEXT NOT NULL,mastery REAL NOT NULL DEFAULT 0,confidence REAL NOT NULL DEFAULT 0.5,attempts INTEGER NOT NULL DEFAULT 0,errors INTEGER NOT NULL DEFAULT 0,last_reviewed INTEGER,next_review INTEGER,status TEXT NOT NULL DEFAULT 'active',FOREIGN KEY(profile_id) REFERENCES learning_profiles(id));
CREATE TABLE learning_reviews (id INTEGER PRIMARY KEY AUTOINCREMENT,profile_id TEXT NOT NULL,lesson_id INTEGER,topic_id INTEGER,scheduled_at INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'scheduled',score REAL,notes TEXT NOT NULL DEFAULT '',created_at INTEGER NOT NULL,FOREIGN KEY(profile_id) REFERENCES learning_profiles(id));
CREATE TABLE media_assets (id TEXT PRIMARY KEY,type TEXT NOT NULL,mime_type TEXT NOT NULL,filename TEXT NOT NULL,size INTEGER NOT NULL,created_at INTEGER NOT NULL,source TEXT NOT NULL DEFAULT 'professor',r2_key TEXT NOT NULL,content_hash TEXT NOT NULL,analysis_status TEXT NOT NULL DEFAULT 'disabled',analysis_summary TEXT NOT NULL DEFAULT '',temporary INTEGER NOT NULL DEFAULT 0,expires_at INTEGER,access_status TEXT NOT NULL DEFAULT 'private', session_id TEXT, turn_id INTEGER);
CREATE INDEX idx_memories_created ON memories(created_at DESC);
CREATE INDEX idx_memories_kind ON memories(kind);
CREATE UNIQUE INDEX idx_memories_fingerprint ON memories(fingerprint) WHERE fingerprint IS NOT NULL;
CREATE INDEX idx_interactions_created ON interactions(created_at DESC);
CREATE INDEX idx_professor_turns_session ON professor_turns(session_id,created_at);
CREATE INDEX idx_professor_lessons_session ON professor_lessons(session_id,created_at);
CREATE INDEX idx_knowledge_passages_source ON knowledge_passages(source_id,active);
CREATE INDEX idx_knowledge_sources_status ON knowledge_sources(status);
CREATE INDEX idx_learning_topics_profile ON learning_topics(profile_id,status);
CREATE INDEX idx_learning_reviews_due ON learning_reviews(profile_id,status,scheduled_at);
CREATE UNIQUE INDEX idx_media_assets_hash ON media_assets(content_hash);