#!/usr/bin/env python3
"""Train a MEL QLoRA adapter on a GPU and emit fail-closed evidence.

The CUDA path uses a 4-bit NF4-quantized base model so the MEL Mistral 7B
adapter can be trained on constrained GPUs such as a T4/L4. This script
deliberately writes TRAINED_UNBENCHMARKED, never "successful". Promotion is a
separate runtime step and requires benchmark gain + compatibility.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import platform
import random
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_BASE = "mistralai/Mistral-7B-Instruct-v0.2"
DEFAULT_RUNTIME = "@cf/mistral/mistral-7b-instruct-v0.2-lora"
MAX_RANK = 32
DEFAULT_MAX_LENGTH = 2048
TARGET_MODULES = ["q_proj", "v_proj"]


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return "sha256:" + h.hexdigest()


def sha256_json(value) -> str:
    text = json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return "sha256:" + hashlib.sha256(text.encode("utf-8")).hexdigest()


def load_and_validate_plan(path: Path, *, dataset_digest: str, examples: int, args):
    if not path.is_file():
        raise SystemExit("LORA_PLAN_NOT_FOUND")
    plan = json.loads(path.read_text(encoding="utf-8"))
    manifest = plan.get("training_manifest")
    if not isinstance(manifest, dict):
        raise SystemExit("LORA_TRAINING_MANIFEST_REQUIRED")
    manifest_digest = sha256_json(manifest)
    if manifest_digest != str(plan.get("training_manifest_digest", "")).lower():
        raise SystemExit("LORA_TRAINING_MANIFEST_DIGEST_INVALID")
    expected = {
        "dataset_digest": dataset_digest,
        "examples": examples,
        "base_model": args.base_model,
        "runtime_model": args.runtime_model,
        "runtime": "cloudflare-workers-ai",
        "method": "lora",
        "rank": args.rank,
        "alpha": args.alpha,
        "dropout": args.dropout,
        "learning_rate": args.learning_rate,
        "epochs": int(args.epochs),
        "quantization": "none",
        "target_modules": TARGET_MODULES,
        "seed": args.seed,
    }
    for key, value in expected.items():
        if manifest.get(key) != value:
            raise SystemExit(f"LORA_PLAN_MISMATCH:{key}")
    if str(plan.get("dataset_digest", "")) != dataset_digest:
        raise SystemExit("LORA_DATASET_MISMATCH")
    if int(plan.get("examples", -1)) != examples:
        raise SystemExit("LORA_EXAMPLE_COUNT_MISMATCH")
    if not plan.get("readiness", {}).get("ready_for_training"):
        raise SystemExit("LORA_PLAN_NOT_READY")
    return plan


def require_gpu(torch, allow_cpu: bool) -> None:
    if torch.cuda.is_available():
        return
    if allow_cpu:
        return
    raise SystemExit(
        "GPU_REQUIRED_FOR_QLORA_TRAINING: no CUDA GPU detected. "
        "Use a compatible GPU runner; do not treat a prepared plan as trained weights."
    )


def load_rows(path: Path):
    rows = []
    with path.open("r", encoding="utf-8") as fh:
        for lineno, line in enumerate(fh, 1):
            line = line.strip()
            if not line:
                continue
            row = json.loads(line)
            messages = row.get("messages")
            if not isinstance(messages, list) or not messages:
                raise ValueError(f"invalid messages at line {lineno}")
            rows.append(row)
    if len(rows) < 50:
        raise SystemExit(f"LORA_DATASET_TOO_SMALL: {len(rows)} examples; minimum is 50")
    return rows


def select_rows(rows, max_samples: int, seed: int):
    if max_samples <= 0 or max_samples >= len(rows):
        return rows, "full"
    rng = random.Random(seed)
    indexes = rng.sample(range(len(rows)), max_samples)
    indexes.sort()
    return [rows[i] for i in indexes], f"deterministic-random-{max_samples}"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset", required=True, help="JSONL with one {'messages': [...]} object per line")
    ap.add_argument("--plan", required=True, help="Canonical plan JSON generated by scripts/create-lora-plan.mjs")
    ap.add_argument("--output", required=True)
    ap.add_argument("--base-model", default=DEFAULT_BASE)
    ap.add_argument("--base-model-path", default="", help="Optional local/offline path for loading the approved base model weights while preserving canonical provenance.")
    ap.add_argument("--runtime-model", default=DEFAULT_RUNTIME)
    ap.add_argument("--rank", type=int, default=8)
    ap.add_argument("--alpha", type=int, default=16)
    ap.add_argument("--dropout", type=float, default=0.05)
    ap.add_argument("--epochs", type=float, default=2.0)
    ap.add_argument("--learning-rate", type=float, default=2e-4)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--max-length", type=int, default=DEFAULT_MAX_LENGTH)
    ap.add_argument(
        "--max-samples",
        type=int,
        default=0,
        help="Deterministically sample N rows for a smoke run; 0 trains the full dataset.",
    )
    ap.add_argument("--gradient-accumulation-steps", type=int, default=8)
    ap.add_argument("--save-steps", type=int, default=250)
    ap.add_argument(
        "--stage",
        choices=["uncensored", "uncensored-continue", "agentic"],
        default="uncensored",
        help="Training lineage stage. uncensored-continue resumes an existing UNCENSORED adapter without overwriting it.",
    )
    ap.add_argument(
        "--parent-adapter-dir",
        default="",
        help="Parent PEFT adapter directory for uncensored-continue or agentic.",
    )
    ap.add_argument(
        "--parent-artifact-digest",
        default="",
        help="Exact sha256 digest of the parent adapter_model.safetensors.",
    )
    ap.add_argument(
        "--resume-from-checkpoint",
        default="",
        help="Optional Trainer checkpoint path, useful on preemptible/free GPU sessions.",
    )
    ap.add_argument(
        "--allow-cpu",
        action="store_true",
        help="Explicitly allow impractical unquantized CPU debug training; CUDA uses QLoRA.",
    )
    args = ap.parse_args()

    if not 1 <= args.rank <= MAX_RANK:
        raise SystemExit(f"LORA_RANK_INVALID: rank must be in [1,{MAX_RANK}]")
    if args.max_length < 128:
        raise SystemExit("LORA_MAX_LENGTH_INVALID: max-length must be >= 128")
    if args.max_samples < 0:
        raise SystemExit("LORA_MAX_SAMPLES_INVALID: max-samples must be >= 0")
    if args.gradient_accumulation_steps < 1:
        raise SystemExit("LORA_GRADIENT_ACCUMULATION_INVALID")
    if args.save_steps < 1:
        raise SystemExit("LORA_SAVE_STEPS_INVALID")
    if args.stage in {"agentic", "uncensored-continue"} and (not args.parent_adapter_dir or not args.parent_artifact_digest):
        raise SystemExit("LORA_PARENT_ADAPTER_REQUIRED")
    if args.stage == "uncensored" and (args.parent_adapter_dir or args.parent_artifact_digest):
        raise SystemExit("UNCENSORED_STAGE_MUST_NOT_HAVE_PARENT")
    if args.base_model != DEFAULT_BASE or args.runtime_model != DEFAULT_RUNTIME:
        raise SystemExit(
            "LORA_MODEL_PAIR_NOT_APPROVED: this trainer is pinned to the currently "
            "approved MEL/Cloudflare LoRA model pair. Change code + tests before changing the pair."
        )

    model_load_source = args.base_model
    if args.base_model_path:
        local_base = Path(args.base_model_path).resolve()
        if not local_base.is_dir():
            raise SystemExit("LORA_BASE_MODEL_PATH_NOT_FOUND")
        required_local = ["config.json", "tokenizer_config.json"]
        missing_local = [name for name in required_local if not (local_base / name).is_file()]
        if missing_local:
            raise SystemExit("LORA_BASE_MODEL_PATH_INCOMPLETE:" + ",".join(missing_local))
        model_load_source = str(local_base)

    dataset_path = Path(args.dataset).resolve()
    output_dir = Path(args.output).resolve()
    if not dataset_path.is_file():
        raise SystemExit("LORA_DATASET_NOT_FOUND")

    all_rows = load_rows(dataset_path)
    source_examples = len(all_rows)
    rows, selection = select_rows(all_rows, args.max_samples, args.seed)
    dataset_digest = sha256_file(dataset_path)
    plan_path = Path(args.plan).resolve()
    plan = load_and_validate_plan(
        plan_path,
        dataset_digest=dataset_digest,
        examples=len(rows),
        args=args,
    )

    try:
        import torch
        import bitsandbytes
        import datasets
        import peft
        import transformers
        from datasets import Dataset
        from peft import LoraConfig, PeftModel, get_peft_model, prepare_model_for_kbit_training
        from transformers import (
            AutoModelForCausalLM,
            AutoTokenizer,
            BitsAndBytesConfig,
            DataCollatorForLanguageModeling,
            Trainer,
            TrainerCallback,
            TrainingArguments,
            set_seed,
        )
    except ImportError as exc:
        raise SystemExit(
            "LORA_TRAINING_DEPENDENCIES_MISSING: install torch, transformers, datasets, "
            "peft, accelerate, bitsandbytes and safetensors"
        ) from exc

    require_gpu(torch, args.allow_cpu)
    set_seed(args.seed)
    cuda = bool(torch.cuda.is_available())
    bf16 = bool(cuda and torch.cuda.is_bf16_supported())
    compute_dtype = torch.bfloat16 if bf16 else (torch.float16 if cuda else torch.float32)

    tokenizer = AutoTokenizer.from_pretrained(model_load_source, use_fast=True, local_files_only=bool(args.base_model_path))
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    if cuda:
        quantization_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_use_double_quant=True,
            bnb_4bit_compute_dtype=compute_dtype,
        )
        model = AutoModelForCausalLM.from_pretrained(
            model_load_source,
            quantization_config=quantization_config,
            torch_dtype=compute_dtype,
            device_map="auto",
            local_files_only=bool(args.base_model_path),
        )
        model = prepare_model_for_kbit_training(
            model,
            use_gradient_checkpointing=True,
        )
        training_mode = "qlora-4bit-nf4"
    else:
        model = AutoModelForCausalLM.from_pretrained(
            model_load_source,
            torch_dtype=torch.float32,
            local_files_only=bool(args.base_model_path),
        )
        model.gradient_checkpointing_enable()
        training_mode = "cpu-fp32-debug"

    model.config.use_cache = False
    config = LoraConfig(
        r=args.rank,
        lora_alpha=args.alpha,
        lora_dropout=args.dropout,
        target_modules=TARGET_MODULES,
        bias="none",
        task_type="CAUSAL_LM",
    )
    if args.stage in {"agentic", "uncensored-continue"}:
        parent_dir = Path(args.parent_adapter_dir).resolve()
        parent_cfg = parent_dir / "adapter_config.json"
        parent_weights = parent_dir / "adapter_model.safetensors"
        if not parent_cfg.is_file() or not parent_weights.is_file():
            raise SystemExit("AGENTIC_PARENT_ARTIFACT_MISSING")
        if sha256_file(parent_weights) != args.parent_artifact_digest.lower():
            raise SystemExit("AGENTIC_PARENT_ARTIFACT_DIGEST_MISMATCH")
        parent_data = json.loads(parent_cfg.read_text(encoding="utf-8"))
        if str(parent_data.get("base_model_name_or_path") or "") != args.base_model:
            raise SystemExit("AGENTIC_PARENT_BASE_MODEL_MISMATCH")
        if int(parent_data.get("r") or 0) != args.rank:
            raise SystemExit("AGENTIC_PARENT_RANK_MISMATCH")
        model = PeftModel.from_pretrained(model, str(parent_dir), is_trainable=True)
    else:
        model = get_peft_model(model, config)

    render_stats = {"native_chat_template": 0, "role_preserving_fallback": 0}

    def render_messages(messages):
        try:
            text = tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=False,
            )
            render_stats["native_chat_template"] += 1
            return text
        except Exception:
            # Some source corpora legitimately contain system/tool roles that
            # Mistral's native template may reject. Preserve every source
            # content string and its turn order; only add explicit role
            # delimiters so no turn is deleted, merged, paraphrased or moved.
            chunks = []
            for turn in messages:
                role = str(turn.get("role") or "unknown")
                content = turn.get("content")
                if not isinstance(content, str):
                    content = json.dumps(content, ensure_ascii=False, separators=(",", ":"))
                chunks.append(f"[{role.upper()}]\n{content}\n")
            if tokenizer.eos_token:
                chunks.append(tokenizer.eos_token)
            render_stats["role_preserving_fallback"] += 1
            return "".join(chunks)

    def render(row):
        text = render_messages(row["messages"])
        tokenized = tokenizer(
            text,
            truncation=True,
            max_length=args.max_length,
        )
        tokenized["labels"] = list(tokenized["input_ids"])
        return tokenized

    raw_dataset = Dataset.from_list(rows)
    ds = raw_dataset.map(render, remove_columns=raw_dataset.column_names)
    output_dir.mkdir(parents=True, exist_ok=True)

    training_args = TrainingArguments(
        output_dir=str(output_dir),
        num_train_epochs=args.epochs,
        learning_rate=args.learning_rate,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        gradient_checkpointing=True,
        optim="paged_adamw_8bit" if cuda else "adamw_torch",
        logging_steps=10,
        save_strategy="steps",
        save_steps=args.save_steps,
        save_total_limit=2,
        report_to=[],
        seed=args.seed,
        data_seed=args.seed,
        fp16=bool(cuda and not bf16),
        bf16=bf16,
        remove_unused_columns=False,
    )
    collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

    training_started_path = output_dir / "training-started.json"
    training_progress_path = output_dir / "training-progress.jsonl"

    def emit_training_progress(event: str, **payload) -> None:
        record = {
            "schema": "mel.lora-training-progress.v1",
            "event": event,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            **payload,
        }
        with training_progress_path.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(record, ensure_ascii=False, sort_keys=True) + "\n")
            fh.flush()
        print("MEL_TRAINING_PROGRESS " + json.dumps(record, ensure_ascii=False, sort_keys=True), flush=True)

    class MelTrainingProgressCallback(TrainerCallback):
        def on_train_begin(self, args_, state, control, **kwargs):
            emit_training_progress(
                "TRAIN_BEGIN",
                global_step=int(state.global_step or 0),
                epoch=float(state.epoch or 0.0),
                max_steps=int(state.max_steps or 0),
            )
            return control

        def on_step_end(self, args_, state, control, **kwargs):
            emit_training_progress(
                "STEP",
                global_step=int(state.global_step or 0),
                epoch=float(state.epoch or 0.0),
                max_steps=int(state.max_steps or 0),
            )
            return control

        def on_log(self, args_, state, control, logs=None, **kwargs):
            logs = dict(logs or {})
            emit_training_progress(
                "LOG",
                global_step=int(state.global_step or 0),
                epoch=float(state.epoch or 0.0),
                loss=logs.get("loss"),
                learning_rate=logs.get("learning_rate"),
                grad_norm=logs.get("grad_norm"),
            )
            return control

        def on_train_end(self, args_, state, control, **kwargs):
            emit_training_progress(
                "TRAIN_END",
                global_step=int(state.global_step or 0),
                epoch=float(state.epoch or 0.0),
                max_steps=int(state.max_steps or 0),
            )
            return control

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=ds,
        data_collator=collator,
        callbacks=[MelTrainingProgressCallback()],
    )

    training_started = {
        "schema": "mel.lora-training-started.v1",
        "status": "TRAINING_STARTED",
        "started_at": datetime.now(timezone.utc).isoformat(),
        "stage": args.stage,
        "plan_id": plan["id"],
        "dataset_digest": dataset_digest,
        "examples": len(rows),
        "epochs": args.epochs,
        "max_length": args.max_length,
        "gradient_accumulation_steps": args.gradient_accumulation_steps,
        "training_mode": training_mode,
        "cuda_available": cuda,
        "gpu": torch.cuda.get_device_name(0) if cuda else None,
    }
    training_started_path.write_text(
        json.dumps(training_started, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    emit_training_progress("TRAINING_STARTED", **training_started)
    print("TRAINING_STARTED " + json.dumps(training_started, ensure_ascii=False, sort_keys=True), flush=True)

    train_result = trainer.train(
        resume_from_checkpoint=args.resume_from_checkpoint or None
    )
    model.save_pretrained(output_dir, safe_serialization=True)
    tokenizer.save_pretrained(output_dir)

    adapter_model = output_dir / "adapter_model.safetensors"
    adapter_config = output_dir / "adapter_config.json"
    if not adapter_model.is_file() or not adapter_config.is_file():
        raise SystemExit("LORA_ARTIFACT_MISSING_AFTER_TRAINING")

    cfg = json.loads(adapter_config.read_text(encoding="utf-8"))
    cfg["model_type"] = "mistral"
    cfg["base_model_name_or_path"] = args.base_model
    adapter_config.write_text(
        json.dumps(cfg, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    evidence = {
        "schema": "mel.lora-training-evidence.v3",
        "status": "TRAINED_UNBENCHMARKED",
        "stage": args.stage,
        "parent_artifact_digest": args.parent_artifact_digest.lower() or None,
        "trained_at": datetime.now(timezone.utc).isoformat(),
        "plan_id": plan["id"],
        "lineage": {
            "stage": args.stage,
            "parent_adapter_dir": Path(args.parent_adapter_dir).name if args.parent_adapter_dir else None,
            "parent_artifact_digest": args.parent_artifact_digest.lower() or None,
        },
        "training_manifest_digest": plan["training_manifest_digest"],
        "dataset_digest": plan["dataset_digest"],
        "base_model": args.base_model,
        "runtime_model": args.runtime_model,
        "runtime": "cloudflare-workers-ai",
        "training_mode": training_mode,
        "dataset": {
            "path": dataset_path.name,
            "source_examples": source_examples,
            "examples": len(rows),
            "selection": selection,
            "digest": dataset_digest,
        },
        "quantization": {
            "enabled": cuda,
            "bits": 4 if cuda else None,
            "type": "nf4" if cuda else None,
            "double_quant": bool(cuda),
            "compute_dtype": str(compute_dtype).replace("torch.", ""),
        },
        "hyperparameters": {
            "rank": args.rank,
            "alpha": args.alpha,
            "dropout": args.dropout,
            "epochs": args.epochs,
            "learning_rate": args.learning_rate,
            "seed": args.seed,
            "max_length": args.max_length,
            "gradient_accumulation_steps": args.gradient_accumulation_steps,
            "target_modules": TARGET_MODULES,
            "optimizer": "paged_adamw_8bit" if cuda else "adamw_torch",
        },
        "artifacts": {
            "adapter_model": {
                "file": adapter_model.name,
                "digest": sha256_file(adapter_model),
                "size_bytes": adapter_model.stat().st_size,
            },
            "adapter_config": {
                "file": adapter_config.name,
                "digest": sha256_file(adapter_config),
                "size_bytes": adapter_config.stat().st_size,
            },
            "training_started": {
                "file": training_started_path.name,
                "digest": sha256_file(training_started_path),
                "size_bytes": training_started_path.stat().st_size,
            },
            "training_progress": {
                "file": training_progress_path.name,
                "digest": sha256_file(training_progress_path),
                "size_bytes": training_progress_path.stat().st_size,
            },
        },
        "training_metrics": {
            "train_loss": getattr(train_result, "training_loss", None),
            "global_step": getattr(train_result, "global_step", None),
        },
        "base_model_loading": {
            "canonical_id": args.base_model,
            "local_offline": bool(args.base_model_path),
            "local_source_name": Path(args.base_model_path).name if args.base_model_path else None,
        },
        "rendering": {
            "mode": "native-chat-template-with-role-preserving-fallback-v1",
            "native_chat_template_rows": render_stats["native_chat_template"],
            "role_preserving_fallback_rows": render_stats["role_preserving_fallback"],
            "source_content_rewritten": False,
            "turn_order_changed": False,
        },
        "environment": {
            "python": platform.python_version(),
            "torch": getattr(torch, "__version__", "unknown"),
            "transformers": getattr(transformers, "__version__", "unknown"),
            "datasets": getattr(datasets, "__version__", "unknown"),
            "peft": getattr(peft, "__version__", "unknown"),
            "bitsandbytes": getattr(bitsandbytes, "__version__", "unknown"),
            "cuda_available": cuda,
            "gpu": torch.cuda.get_device_name(0) if cuda else None,
            "gpu_count": torch.cuda.device_count() if cuda else 0,
        },
        "promotion": {
            "approved": False,
            "reason": "BENCHMARK_REQUIRED",
            "minimum_measured_gain": 0.02,
        },
    }
    (output_dir / "training-evidence.json").write_text(
        json.dumps(evidence, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    artifact_evidence = {
        "id": "artifact-" + evidence["artifacts"]["adapter_model"]["digest"].split(":", 1)[1][:16],
        "finetune_id": None,
        "digest": evidence["artifacts"]["adapter_model"]["digest"],
        "base_model": args.base_model,
        "runtime_model": args.runtime_model,
        "runtime": "cloudflare-workers-ai",
        "size_bytes": evidence["artifacts"]["adapter_model"]["size_bytes"],
        "rank": args.rank,
        "format": "safetensors",
        "uri": None,
        "dataset_digest": plan["dataset_digest"],
        "training_manifest_digest": plan["training_manifest_digest"],
        "plan_id": plan["id"],
        "stage": args.stage,
        "parent_artifact_digest": args.parent_artifact_digest.lower() or None,
    }
    (output_dir / "artifact-evidence.json").write_text(
        json.dumps(artifact_evidence, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (output_dir / "lora-plan.json").write_text(
        json.dumps(plan, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(evidence, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
