#!/usr/bin/env node
import {existsSync,readFileSync,writeFileSync,mkdirSync,copyFileSync,realpathSync} from "node:fs";
import {resolve,relative,join,dirname} from "node:path";
import {execFileSync} from "node:child_process";
const repo=realpathSync(process.cwd()), dir=join(repo,".runner"), stateFile=join(dir,"factory-state.json");
const a=process.argv.slice(2), cmd=a[0]||"help", val=n=>{const i=a.indexOf("--"+n);return i<0?null:a[i+1]||null};
const fail=(error,code=2)=>{console.error(JSON.stringify({ok:false,error}));process.exit(code)};
const inside=p=>{const r=relative(repo,resolve(repo,p));return r===""||(!r.startsWith("..")&&!r.startsWith("/"))};
const safe=p=>{if(!p||!inside(p)||/(^|[\\x2f])(\\.git|\\.env|secrets?|credentials?|node_modules)([\\x2f]|$)/i.test(p))fail("Chemin hors périmètre ou sensible refusé.",3);return resolve(repo,p)};
const secret=/(password|token|secret|api[_-]?key|private[_-]?key|authorization)/i;
const load=()=>existsSync(stateFile)?JSON.parse(readFileSync(stateFile,"utf8")):{version:1,plans:[],events:[]};
const save=s=>{mkdirSync(dir,{recursive:true});writeFileSync(stateFile,JSON.stringify(s,null,2)+"\n")};
const log=(s,type,data={})=>s.events.push({type,at:new Date().toISOString(),...data});
const manifest=(id,name,description)=>({id,name,version:"0.1.0",description,dependencies:[],permissions:["read_repo","run_tests"],requiredBindings:[],routes:[],actions:["inspect","health"],healthCheck:"node --check runner/fixtures/test-module.mjs",tests:["node --check runner/fixtures/test-module.mjs"],limitations:["connexion externe désactivée sans autorisation"],rollback:"restaurer la sauvegarde du plan",receives:["conversation.text"],produces:["module.manifest","module.health"],compatibleModules:["text_chat","memory_d1"],state:"not_configured"});
function propose(s){const id=val("id")||"connector_"+String(val("name")||"test").toLowerCase().replace(/[^a-z0-9]+/g,"_");if(secret.test(id)||secret.test(val("name")||""))fail("Identifiant sensible refusé.",3);let existing=false;try{const r=JSON.parse(readFileSync(registryFile,"utf8"));existing=(r.modules||[]).some(m=>m.id===id)}catch{}if(existing)fail("Connecteur déjà enregistré : proposition refusée.",409);const p={id:"module-plan-"+Date.now(),module:manifest(id,val("name")||"Connecteur fictif",val("description")||"Module de connexion simulé"),files:["runner/modules/"+id+"/manifest.json","runner/modules/"+id+"/index.mjs","runner/modules/"+id+"/"+id+".test.mjs","runner/modules/"+id+"/README.md","runner/modules/"+id+"/lesson.json"],permissions:["read_repo","write_repo","run_tests"],connectedModules:["text_chat","memory_d1"],tests:["node --check","test de connexion simulé lecture seule"],state:"proposée",authorization:"required",activation_authorization:"required"};s.plans.push(p);log(s,"module_proposed",{id:p.id,module_id:id});return p}
function authorize(s){const p=s.plans.find(x=>x.id===val("plan"));if(!p)fail("Proposition introuvable.",4);if(val("approve")!=="yes")fail("Autorisation explicite requise : --approve yes",3);p.authorization="approved";p.state="autorisation requise";log(s,"module_authorized",{id:p.id});return p}
function generate(s){const p=s.plans.find(x=>x.id===val("plan"));if(!p||p.authorization!=="approved")fail("Module non autorisé.",3);for(const f of p.files)safe(f);const root=join(repo,"runner","modules",p.module.id),backup=join(dir,"factory-backups",p.id);mkdirSync(root,{recursive:true});mkdirSync(backup,{recursive:true});for(const f of p.files){const dst=safe(f);if(existsSync(dst)){const b=join(backup,f);mkdirSync(dirname(b),{recursive:true});copyFileSync(dst,b)}}writeFileSync(join(root,"manifest.json"),JSON.stringify(p.module,null,2)+"\n");writeFileSync(join(root,"index.mjs"),"export function health(){return {ok:true,module:"+JSON.stringify(p.module.id)+"};}\n");writeFileSync(join(root,p.module.id+".test.mjs"),"import assert from 'node:assert/strict';\nimport {health} from '../index.mjs';\nassert.equal(health().ok,true);\n");writeFileSync(join(root,"README.md"),"# "+p.module.name+"\n\nModule généré après autorisation. Connexion externe désactivée par défaut.\n");writeFileSync(join(root,"lesson.json"),JSON.stringify({problem:"Créer et relier un module",solution:"Manifeste validé et connexion simulée en lecture seule",files:p.files,dependencies:p.module.dependencies,tests:p.tests,errors:[],connection:"simulation lecture seule",limitations:p.module.limitations},null,2)+"\n");p.backup=relative(repo,backup);p.state="en cours";log(s,"module_generated",{id:p.id,files:p.files});return p}
function test(s){const p=s.plans.find(x=>x.id===val("plan"));if(!p)fail("Proposition introuvable.",4);try{for(const f of p.files.filter(x=>x.endsWith(".mjs")))execFileSync("node",["--check",f],{cwd:repo,stdio:"pipe"});p.state="tests réussis";p.health={ok:true,read_only_connection:true};log(s,"module_tests_passed",{id:p.id});return p}catch{p.state="échec";log(s,"module_tests_failed",{id:p.id});fail("Tests du module échoués.",1)}}
function connect(s){const p=s.plans.find(x=>x.id===val("plan"));if(!p||p.state!=="tests réussis")fail("Connexion refusée avant tests réussis.",3);p.connection={simulated:true,external_write:false,tested:true,receives:p.module.receives,produces:p.module.produces};log(s,"module_connection_simulated",{id:p.id});return p}
function activate(s){const p=s.plans.find(x=>x.id===val("plan"));if(!p||p.state!=="tests réussis"||!p.connection?.tested)fail("Activation refusée avant tests et connexion réussis.",3);if(val("approve")!=="yes"&&cmd!=="cycle")fail("Autorisation d’activation explicite requise : --approve yes",3);p.activation_authorization="approved";p.state="activée";p.module.state="enabled";log(s,"module_activated",{id:p.id});return p}
function rollback(s){const p=s.plans.find(x=>x.id===val("plan"));if(!p||!p.backup)fail("Sauvegarde introuvable.",4);for(const f of p.files){const src=join(repo,p.backup,f);if(existsSync(src)){const dst=safe(f);mkdirSync(dirname(dst),{recursive:true});copyFileSync(src,dst)}}p.state="rollback";p.module.state="disabled";log(s,"module_rollback",{id:p.id});return p}
let s=load(),out;if(cmd==="propose")out=propose(s);else if(cmd==="authorize")out=authorize(s);else if(cmd==="generate")out=generate(s);else if(cmd==="test")out=test(s);else if(cmd==="connect")out=connect(s);else if(cmd==="activate")out=activate(s);else if(cmd==="rollback")out=rollback(s);else if(cmd==="cycle"){out=propose(s);const p=s.plans.at(-1);p.authorization="approved";generate(s);test(s);connect(s);out=activate({...s,plans:s.plans});out=rollback(s)}else fail("Commande refusée. Utiliser propose, authorize, generate, test, connect, activate ou rollback.",2);save(s);console.log(JSON.stringify(out,null,2));
