import fs from 'node:fs/promises'; import path from 'node:path'; import {spawn} from 'node:child_process';
import { createDefaultCapabilityBus } from '../capabilities/default-bus.js';
const SECRET=/(^|[._-])(env|dev\.vars|pem|key|credentials?)($|[._-])|token|password|secret|api[_-]?key|authorization/i;
const TESTS=new Map([['test', ['npm','test']],['test:mel',['npm','run','test:mel']],['test:integration',['npm','run','test:integration']],['test:acceptance',['npm','run','test:acceptance']],['test:smoke',['npm','run','test:smoke']],['test:mvp',['npm','run','test:mvp']],['test:routes',['npm','run','test:routes']]]);
export class LocalDevBridge {
 constructor({repoRoot=process.cwd(),candidateRoot=path.join(repoRoot,'.mel-dev-candidates')}={}) { this.repoRoot=path.resolve(repoRoot); this.candidateRoot=path.resolve(candidateRoot); this.candidates=new Map(); this.bus=createDefaultCapabilityBus(); this.registerCapabilities(); }
 registerCapabilities(){const defs=[['code.status',async()=>({result:await this.status()})],['code.tree',async()=>({result:await this.tree()})],['code.search',async i=>({result:await this.search(i.query)})],['code.read',async i=>({content:await this.readFile(i.path)})],['code.diff',async()=>({result:await this.diff()})],['dev.create_candidate',async i=>this.createCandidate(i.job_id)],['dev.apply_change',async i=>this.writeFileCandidate(i.job_id,i.path,i.content)],['dev.test',async i=>this.runTests(i.command,i.job_id)],['dev.report',async i=>this.report(i.job_id)],['dev.rollback',async i=>this.rollbackCandidate(i.job_id)],['dev.commit',async i=>{if(i.approved!==true)throw Object.assign(new Error('APPROVAL_REQUIRED'),{code:'APPROVAL_REQUIRED'});const c=this.candidate(i.job_id);c.status='APPROVED';return this.commitCandidate(i.job_id,i.files,i.message);}]];for(const [id,fn] of defs)this.bus.discover({id,name:id,category:'dev',version:'1.0.0',provider:'local-bridge',description:'Bounded local development operation',input_schema:{type:'object',additionalProperties:true},output_schema:{type:'object',additionalProperties:true},risk:id==='dev.commit'?'HIGH':'LOW',permissions:[],health:'HEALTHY',enabled:true},fn);}
 safe(rel){if(!rel||path.isAbsolute(rel)||SECRET.test(rel))throw Object.assign(new Error('PATH_DENIED'),{code:'PATH_DENIED'});const p=path.resolve(this.repoRoot,rel);if(p!==this.repoRoot&&!p.startsWith(this.repoRoot+path.sep))throw Object.assign(new Error('OUTSIDE_REPO_DENIED'),{code:'OUTSIDE_REPO_DENIED'});return p;}
 async status(){return this.exec(['git','status','--short']);} async diff(){return this.exec(['git','diff','--check']);} async tree(){return (await fs.readdir(this.repoRoot,{withFileTypes:true})).map(x=>x.name).filter(x=>!SECRET.test(x));} async currentBranch(){return (await this.exec(['git','branch','--show-current'])).stdout.trim();} async log(){return this.exec(['git','log','--oneline','-10']);}
 async search(query){const q=String(query||'');if(!q||SECRET.test(q))throw Object.assign(new Error('SEARCH_DENIED'),{code:'SEARCH_DENIED'});return this.exec(['rg','-n','--hidden','--glob','!.git','--glob','!.mel-dev-candidates',q,'.']);}
 async readFile(rel){return fs.readFile(this.safe(rel),'utf8');}
 async createCandidate(jobId){if(!/^[A-Za-z0-9_-]+$/.test(jobId))throw new Error('INVALID_JOB_ID');const dir=path.join(this.candidateRoot,jobId);await fs.rm(dir,{recursive:true,force:true});await fs.mkdir(dir,{recursive:true});await this.git(['init','-q'],dir);await this.git(['config','user.email','mel-bridge@localhost'],dir);await this.git(['config','user.name','MEL Dev Bridge'],dir);await fs.writeFile(path.join(dir,'.candidate'),'stable repository snapshot\n');await this.git(['add','.candidate'],dir);await this.git(['commit','-qm','candidate baseline'],dir);const branch=`mel-dev/${jobId}`;this.candidates.set(jobId,{jobId,dir,branch,base:await this.currentBranch().catch(()=>''),status:'CANDIDATE'});return this.candidates.get(jobId);}
 candidate(jobId){const c=this.candidates.get(jobId);if(!c)throw Object.assign(new Error('CANDIDATE_NOT_FOUND'),{code:'CANDIDATE_NOT_FOUND'});return c;}
 async writeFileCandidate(jobId,rel,content){const c=this.candidate(jobId);if(typeof content!=='string'||content.length>200000)throw new Error('INVALID_CANDIDATE_WRITE');if(SECRET.test(rel))throw Object.assign(new Error('PATH_DENIED'),{code:'PATH_DENIED'});const target=path.resolve(c.dir,rel);if(!target.startsWith(c.dir+path.sep))throw Object.assign(new Error('OUTSIDE_CANDIDATE_DENIED'),{code:'OUTSIDE_CANDIDATE_DENIED'});await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,content);return {jobId,branch:c.branch,path:rel};}
 async runTests(name,jobId=null){const cmd=TESTS.get(name);if(!cmd)throw Object.assign(new Error('COMMAND_NOT_ALLOWED'),{code:'COMMAND_NOT_ALLOWED'});const cwd=jobId?this.candidate(jobId).dir:this.repoRoot;return this.exec(cmd,cwd);}
 async commitCandidate(jobId,files=[],message='MEL candidate change'){const c=this.candidate(jobId);if(c.status!=='APPROVED')throw Object.assign(new Error('APPROVAL_REQUIRED'),{code:'APPROVAL_REQUIRED'});const check=await this.git(['diff','--check'],c.dir);if(check.exit_code!==0)throw new Error('DIFF_CHECK_FAILED');const safe=files.length?files:['.candidate'];for(const f of safe){if(path.isAbsolute(f)||f.includes('..')||SECRET.test(f))throw Object.assign(new Error('PATH_DENIED'),{code:'PATH_DENIED'});}await this.git(['add','--',...safe],c.dir);const msg=String(message).replace(/[\r\n]/g,' ').slice(0,120)||'MEL candidate change';await this.git(['commit','-m',msg],c.dir);c.status='COMMITTED';return {jobId,branch:c.branch,status:'COMMITTED',commit:(await this.git(['rev-parse','HEAD'],c.dir)).stdout.trim()};}
 async report(jobId){const c=this.candidate(jobId);return {jobId,branch:c.branch,status:c.status,base:c.base,diff:await this.diff().catch(e=>({error:e.code||e.message}))};}
 async rollbackCandidate(jobId){const c=this.candidate(jobId);await fs.rm(c.dir,{recursive:true,force:true});this.candidates.delete(jobId);return {jobId,status:'ROLLED_BACK'};}
 async exec(args,cwd=this.repoRoot){const allowed=(args[0]==='git'&&['status','diff','log','branch'].includes(args[1]))||(args[0]==='rg')||(args[0]==='npm'&&((args[1]==='test')||(args[1]==='run'&&TESTS.has(args[2]))));if(!allowed)throw Object.assign(new Error('COMMAND_NOT_ALLOWED'),{code:'COMMAND_NOT_ALLOWED'});return new Promise((resolve,reject)=>{const p=spawn(args[0],args.slice(1),{cwd, shell:false});let stdout='',stderr='';p.stdout.on('data',d=>stdout+=d);p.stderr.on('data',d=>stderr+=d);p.on('error',reject);p.on('close',code=>resolve({command:args.join(' '),exit_code:code,stdout:stdout.slice(0,20000),stderr:stderr.slice(0,20000)}));});}
 async git(args,cwd){return new Promise((resolve,reject)=>{const p=spawn('git',args,{cwd,shell:false});let stdout='',stderr='';p.stdout.on('data',d=>stdout+=d);p.stderr.on('data',d=>stderr+=d);p.on('error',reject);p.on('close',code=>resolve({exit_code:code,stdout,stderr}));});}
}
